services:
  webscraping:
    image: 192.168.1.192:5000/webscraping:latest
    container_name: webscraping
    restart: unless-stopped
    networks:
      - front

networks:
    front:
        external: true
        name: front
