name: Deploy (only on app-vm-01)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # Target a specific self-hosted runner by label
    runs-on: [ self-hosted, linux, x64, app-vm-01 ]
    steps:
      - name: Deploy app-vm-01
        run: |
          cd /srv/docker-apps-infra
          pwd
          git pull
          ls -la
          cp ops/deploy/app-vm-01.sh . -f
          chmod +x app-vm-01.sh
          ./app-vm-01.sh

