services:
  wordpress:
    image: wordpress:6-php8.2-apache
    container_name: wp_app
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8020:80"
    networks:
      - front

volumes:
  wp_data:

networks:
    front:
        external: true
        name: front
